# Generated by Django 4.0.1 on 2022-02-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
