"""empty message

Revision ID: 69000004b6d4
Revises: 2df3dc5b7eca
Create Date: 2023-01-19 15:06:45.450322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69000004b6d4'
down_revision = '2df3dc5b7eca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_addr', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('ip_addr')

    # ### end Alembic commands ###
